services:
  - type: web
    name: app
    runtime: docker
    dockerfilePath: infra/docker/prod/Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: RUN_MIGRATIONS
        value: "true"
